---
- hosts: all
  user: vagrant
  sudo: yes
  tasks:
    - name: Update apt keys
      command: apt-key update

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=604800 # 1 week in seconds (7*24*3600)  

    - name: ensure nginx installed
      apt: package={{ item }} state=present
      with_items:
      - nginx
      notify:
      - restart nginx
    - name: ensure dependencies are installed
      apt: package={{ item }} state=present
      with_items:
      - solr-tomcat
      - postgresql
      - build-essential
      - git-core
      - memcached
      - libgeoip-dev
      - python-dev
      - python-pip
      - python-lxml
      - python-beautifulsoup
      - python-babel
      - python-imaging
      - python-couchdb
      - python-genshi
      - python-psycopg2
      - python-py
      - python-memcache
      - python-yaml
      - python-simplejson
      - python-sphinx
      - python-celery
      - python-sqlalchemy
      - gunicorn
      - curl 
      - screen

    - include: tasks/db.yml

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
